### ISSUE TITLE
FluentValidationRules assumes all properties are camelcase

### ISSUE THREAD

**Issue by jonmeyerson** [micro-elements/MicroElements.Swashbuckle.FluentValidation#10]
In FluentValidationRules.cs the loop that goes through the validators is converting the property to camelcase which means if the property is not already camel case it will not be picked up and look for matches to the default rules. 
https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/blob/master/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationRules.cs#L74

**Comment by petriashev** [comment]
Do you mean properties like propertyName?

**Comment by jonmeyerson** [comment]
Yes, that is what I mean. For example, if I had a property named 'iFrame' it would not be able find the rule to match it up.

**Comment by petriashev** [comment]
I will fix it on weekends
