### ISSUE TITLE
FluentValidation rules not emited on inherited property in one class, but does in another

### ISSUE THREAD

**Issue by icnocop** [micro-elements/MicroElements.Swashbuckle.FluentValidation#100]
Hi.

I'm experiencing an issue where the FluentValidation rules are not emitted in swagger.json for an inherited property in one class, but those rules are emitted in another class.

I created an example in my fork here:
https://github.com/icnocop/MicroElements.Swashbuckle.FluentValidation

Steps to reproduce:
1. Build and run the SampleWebApi project
2. Expand Issue100 > "POST /api/Issue100/AddMyEntity100" > Parameters > Request Body > Schema > MyEntity100 > person
3. Expand Person100A
4. Expand Person100B
5. Notice the `age` property has the expected FluentValidation rules in `Person100B`, but not in `Person100A`.

Any ideas?

Thank you!

**Comment by petriashev** [comment]
Current state:
![изображение](https://user-images.githubusercontent.com/127600/144720334-f64b44c4-c5de-4c09-8cf5-8b5c1decf63c.png)

Looking for validator for Person100A: (validator not found)
![изображение](https://user-images.githubusercontent.com/127600/144718699-e6b5c37e-601d-45df-926a-258e0fa138d4.png)

**Comment by petriashev** [comment]
GetValidator looks for registered validator for type Person100A and it fails because no real validator registered in factory.
In future we can support PolymorficValidator but now we have workaround:

Solution:
1. Create real class:
![изображение](https://user-images.githubusercontent.com/127600/144720371-a6a814a4-05d9-4d4a-b3c2-3e599bfd33df.png)

2. Move validator from abstract BasePerson100 to MyEntity100 (according FV docs) (OPTIONAL)
```
        [SwaggerDiscriminator("discriminator")]
        [SwaggerSubType(typeof(Person100A), DiscriminatorValue = Person100A.DiscriminatorValue)]
        [SwaggerSubType(typeof(Person100B), DiscriminatorValue = Person100B.DiscriminatorValue)]
        [JsonConverter(typeof(JsonInheritanceConverter), "discriminator")]
        [JsonInheritance(Person100A.DiscriminatorValue, typeof(Person100A))]
        [JsonInheritance(Person100B.DiscriminatorValue, typeof(Person100B))]
        public abstract class BasePerson100
        {
        }

        public class MyEntity100
        {
            public BasePerson100 Person { get; set; }

            [UsedImplicitly]
            public class MyEntity100Validator : AbstractValidator<MyEntity100>
            {
                public MyEntity100Validator()
                {
                    this.RuleFor(x => x.Person)
                        .SetInheritanceValidator(x =>
                        {
                            x.Add<Person100A>(new Person100A.Person100AValidator());
                            x.Add<Person100B>(new Person100B.Person100BValidator());
                        });
                }
            }
        }
```

**Comment by petriashev** [comment]
There is some mismatch between dynamic FluentValidation nature and OpenApi static document generation

**Comment by icnocop** [comment]
Thank you!

After updating the code as suggested, the FV rules are emitted on Person100A as expected.

Thank you again for your help. 🙏

**Comment by petriashev** [comment]
Thank you Rami!
