### ISSUE TITLE
Incorrect Mapping of Properties

### ISSUE THREAD

**Issue by maganuk** [micro-elements/MicroElements.Swashbuckle.FluentValidation#103]
I have the following model:

    public class DataType
    {
      public string Value { get; set; }
    }

    public class Dict
    {
      public DataType Type { get; set; }
      public DataType Value { get; set; }
    }

    public class DictValidator : AbstractValidator<Dict>
    {
      public DictValidator()
      {
        RuleFor(x => x.Type.Value)
          .NotEmpty()
          .NotNull()
          .MaximumLength(100);
      
        RuleFor(x => x.Value.Value)
          .NotEmpty()
          .NotNull()
          .MaximumLength(5000);
      }
    }

AddFluentValidationRulesToSwagger is incorrectly injecting the rules of Type into Values - whereas there are no validations showing up in Type

**Comment by petriashev** [comment]
Thanks for the example!
Current OpenApi will be that:
![изображение](https://user-images.githubusercontent.com/127600/166157693-7e484079-8d9a-4f09-988a-30dd473627d8.png)

OpenApi declares validation in per type basis. So you can declare validator for 'DataType' and for 'Dict'.
If you declare DataType.Value maxLen as 100 then you cant override it in other scheme.

**Comment by petriashev** [comment]
```csharp
#region Solution1: Validator per type

public record DataType100(string Value);
public record DataType5000(string Value);
public record Dict2(DataType100 Type, DataType5000 Value);

public class DataType100Validator : AbstractValidator<DataType100>
{
	public DataType100Validator()
	{
		RuleFor(x => x.Value)
			.NotEmpty()
			.NotNull()
			.MaximumLength(100);
	}
}

public class DataType5000Validator : AbstractValidator<DataType5000>
{
	public DataType5000Validator()
	{
		RuleFor(x => x.Value)
			.NotEmpty()
			.NotNull()
			.MaximumLength(5000);
	}
}      

public class Dict2Validator : AbstractValidator<Dict2>
{
	public Dict2Validator()
	{
		RuleFor(x => x.Type).NotNull();
		RuleFor(x => x.Value).NotNull();
	}
}

#endregion

#region Solution2: use strings

public record Dict3(string Type, string Value);
public class Dict3Validator : AbstractValidator<Dict3>
{
	public Dict3Validator()
	{
		RuleFor(x => x.Type)
			.NotEmpty()
			.NotNull()
			.MaximumLength(100);

		RuleFor(x => x.Value)
			.NotEmpty()
			.NotNull()
			.MaximumLength(5000);
	}
}

#endregion
```

**Comment by maganuk** [comment]
Thanks for the solutions Alexey! Will give this a try
