### ISSUE TITLE
FluentValidation 11.0 support

### ISSUE THREAD

**Issue by buvinghausen** [micro-elements/MicroElements.Swashbuckle.FluentValidation#104]
[Version 11 dropped on Saturday](https://www.nuget.org/packages/FluentValidation/11.0.0)

[The version constraint doesn't allow for users to upgrade currently](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/blob/master/src/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation.csproj#L16)

**Comment by petriashev** [comment]
I tested it on Fv11 and it's working without issues. Pushed new version of package.

**Comment by buvinghausen** [comment]
Ty
