### ISSUE TITLE
ILengthValidator does not work correctly for arrays

### ISSUE THREAD

**Issue by biggik** [micro-elements/MicroElements.Swashbuckle.FluentValidation#107]
Instead of producing maxItems, as follows:
`  "geoTraces": {
            "maxItems": 1000,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/MyClass"
            }
          }`

it productes maxLength - resulting in Swagger UI reporting this as "<= characters" instead of "<= items"

**Comment by biggik** [comment]
Attached is a patch that resolves this issue (I'm not allowed to create a pull request)

[0001-Handle-type-array-for-ILengthValidator.zip](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/files/8863294/0001-Handle-type-array-for-ILengthValidator.zip)
)

**Comment by petriashev** [comment]
Thank you for patch. I will see it tomorrow.
PR in github should be done with fork, no rights needed.

**Comment by biggik** [comment]
Ahh, of course. I createa PR based on my fork
https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/pull/108

**Comment by petriashev** [comment]
Can you provide a sample of validator?
Current `LengthValidator` is only for strings as I know. see: https://docs.fluentvalidation.net/en/latest/built-in-validators.html#maxlength-validator

**Comment by biggik** [comment]
The MaxLength implementation of ILengthValidator is for strings, yes, but the interface can be used for arrays as well.
See the interface here: https://github.com/FluentValidation/FluentValidation/blob/main/src/FluentValidation/Validators/LengthValidator.cs

Note that the code I changed is dealing with ILengthValidator, not the implementation of MaxLengthValidator

Also see https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/blob/master/src/MicroElements.Swashbuckle.FluentValidation/DefaultFluentValidationRuleProvider.cs the implementation for NotEmpty which specifies  MinItems for array types.

If this is not implemented, I don't see how Min/MaxItems can be generated into an OpenAPI spec.

As for a particular implementation my team has been using such validators for a while now to specify a limit on arrays sent through our api, either as [0 ... xxx] or in conjunction with NotEmpty as [1 ... xxx]. 
We have actually used jquery to replace 'characters' with 'items' in the UI, but I feel that this is a better approach. There are also complexities involved with nested objects that have arrays, as they are not present in the DOM when first generated.

If you wish, then I can create a sample to illustrate this

**Comment by petriashev** [comment]
I need an example to write a test. 
As I understand you have custom ILengthValidator for collections?

**Comment by petriashev** [comment]
Alternative: register `FluentValidationRule` with the name you want to replace. (fast solution)

**Comment by biggik** [comment]
I've updated the PR with a unit test

I do not follow your last comment regarding the registration of a FluentValidationRule - can you give an example?

**Comment by petriashev** [comment]
Look here: https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/blob/48cc631eb6f1496812bdeca0c1b815f2ed5507bb/samples/SampleWebApi/Startup.cs#L94

**Comment by petriashev** [comment]
Check v5.7.0 on nuget
