### ISSUE TITLE
Include validation rules from SetValidator() with AbstractValidator validators

### ISSUE THREAD

**Issue by biggik** [micro-elements/MicroElements.Swashbuckle.FluentValidation#110]
Hi there

I created a sample [here](https://github.com/biggik/SwaggerGenTests) to demonstrate the issue we are facing. There is a readme there that fully explains the issue

Brief overview: using AbstractValidator instances with SetValidator doesn't apply restrictions to the swagger spec from the AbstractValidator instance.

There may be alternative ways to achieve this, of which I'm not aware ...

**Comment by petriashev** [comment]
Hello look at https://github.com/FluentValidation/FluentValidation/issues/184
There are two existing options:
- Create ValueObject Address and there will be schema for Address type with needed validations
- Wrap validation rules in extension like Jeremy suggests

I already have a solution for validators that validate simple types. I hope I release it soon

**Comment by biggik** [comment]
Alternatives given are acceptable
