### ISSUE TITLE
Publish MicroElements.NSwag.FluentValidation to nuget.org

### ISSUE THREAD

**Issue by icnocop** [micro-elements/MicroElements.Swashbuckle.FluentValidation#119]
Hi.

I wanted to add a reference to MicroElements.NSwag.FluentValidation in my web application, but the nuget package hasn't been published yet.

Although there are other packages which have been published using a fork of this repository:
https://www.nuget.org/packages/ZymLabs.NSwag.FluentValidation.AspNetCore
https://www.nuget.org/packages/ZymLabs.NSwag.FluentValidation/

I know you're probably already aware of this, and just wanted to open this so it can be tracked.

Is the package published on another public nuget repository like myget.org for example?

Otherwise, the code has to be downloaded and built manually, which makes it somewhat related to https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/issues/109.

Thank you!

**Comment by petriashev** [comment]
Hi, Rami!
I did not published it because it is experimental yet. I began to extract core logic

**Comment by petriashev** [comment]
You can try https://www.myget.org/feed/micro-elements/package/nuget/MicroElements.NSwag.FluentValidation/6.0.0-beta.2
It's in beta yet. My sample web app works (base schema generation)

**Comment by petriashev** [comment]
pushed to nuget

**Comment by icnocop** [comment]
Thank you! 👍
