### ISSUE TITLE
Taking a DbContext dependency in the validator

### ISSUE THREAD

**Issue by MaciejWierzchowski** [micro-elements/MicroElements.Swashbuckle.FluentValidation#14]
Code speaks more than 1000 words:

```
using FluentValidation;
using Microsoft.EntityFrameworkCore;
using System.Threading;
using System.Threading.Tasks;

namespace MyAspNetCore
{
    public class MyValidator : AbstractValidator<MyObject>
    {
        private readonly MyDbContext myDbContext;

        public SeasonValidator(MyDbContext myDbContext)
        {
            this.myDbContext = myDbContext;

            this.RuleFor(x => x.Name).NotEmpty().NotNull().MustAsync(this.NameMustBeUnique).WithMessage("The name must be unique.");
        }

        public async Task<bool> NameMustBeUnique(string name, CancellationToken cancellationToken)
        {
            return !await this.myDbContext.MyObjects.AnyAsync(x => x.Name == name);
        }
    }
}
```

Fails with this:

> MicroElements.Swashbuckle.FluentValidation.FluentValidationRules: Warning: GetValidator for type 'MyAspNetCore.MyObject' fails.
> 
> System.InvalidOperationException: Cannot resolve 'FluentValidation.IValidator`1[MyAspNetCore.MyObject]' from root provider because it requires scoped service 'MyAspNetCore.MyDbContext'.
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
>    at FluentValidation.AspNetCore.ServiceProviderValidatorFactory.CreateInstance(Type validatorType)
>    at FluentValidation.ValidatorFactoryBase.GetValidator(Type type)
>    at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.Apply(Schema schema, SchemaFilterContext context)

I understand why this fails, but any idea on how to solve it? Some fake (unscoped) implementation for the DbContext? Setter injection (but then I need to use a different container)?

**Comment by petriashev** [comment]
The reason is "because it requires scoped service 'MyAspNetCore.MyDbContext'"
You need to register MyDbContext is ServiceCollection

**Comment by MaciejWierzchowski** [comment]
Thanks for the response, but no, not really. The DbContext is registered and the validation using it works.  There was simply no metadata in swagger doc.

The problem is that DbContext is registered as scoped service. And this code (from `FluentValidationRules`)
```
try
{
    validator = _validatorFactory.GetValidator(context.SystemType);
}
   catch (Exception e)
{
    _logger?.LogWarning(0, e, $"GetValidator for type '{context.SystemType}' fails.");
}
```
Runs on application startup to get the metadata out of validators. But by default, MS DI container throws an exception when you try to resolve a scoped service without the scope (i.e. http request). And application startup doesn't run in context of http request, so thus the error.

In any case, I solved this by injecting `Func<MyDbContext>` instead of actual instance of the context, and I think that's the way to go. I think the issue can be closed!
