### ISSUE TITLE
Update to support Swashbuckle.AspNetCore v7.0.0

### ISSUE THREAD

**Issue by marcominerva** [micro-elements/MicroElements.Swashbuckle.FluentValidation#150]
Currently, the library has the following constraint:

`<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="[6.3.0, 7)" />`

Now that **Swashbuckle.AspNetCore v7.0.0** has been released, this prevents the update.

**Comment by daniecas** [comment]
and Swashbuckle.AspNetCore v7.0.0 is required to update to **.net 9**

**Comment by bweber** [comment]
I think this repo is abandoned. We probably need a new community fork of this with a new maintainer.

**Comment by jrgcubano** [comment]
@petriashev Hello. Do you think this is feasible? Is it okay if I create a PR? 

Thanks in advance for your effort.

**Comment by jrgcubano** [comment]
@petriashev Hello,

I have opened a PR with the upgrade https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/pull/151

Let me know if that works for you.

**Comment by IhnatKlimchuk** [comment]
I see 6.1 in `https://www.myget.org/F/micro-elements/api/v3/index.json` but not in Nuget, probably manual script run is required 😔

**Comment by jrgcubano** [comment]
@marcominerva the PR has been merged, you can now close the issue.

**Comment by marcominerva** [comment]
Thank you!

**Comment by Jabulin** [comment]
Hello, there is another problem - now with depended package MicroElements.OpenApi.FluentValidation.
The expected version of the NuGet package is >= 6.1.0, but only version 6.0.0 is available.

**Comment by hummer007** [comment]
![image](https://github.com/user-attachments/assets/32fe8393-2830-4d57-bd85-6776937df22d)

**Comment by jrgcubano** [comment]
@Jabulin @avgalex I just realized the same thing, the process is not publishing MicroElements.OpenApi.FluentValidation to nuget.

**Comment by jrgcubano** [comment]
In theory according to the build process, it seems that it was pushed

![image](https://github.com/user-attachments/assets/1e3a6d76-78d6-40ab-bb5b-7d1f69017ca6)

**Comment by jrgcubano** [comment]
@avgalex 

What's happening is that it's only publishing that package (MicroElements.Swashbuckle.FluentValidation), but not the others (MicroElements.OpenApi.FluentValidation, MicroElements.NSwag.FluentValidation, etc).

**Comment by vchirikov** [comment]
@jrgcubano is right, there is no [MicroElements.OpenApi.FluentValidation 6.1.0](https://www.nuget.org/packages/MicroElements.OpenApi.FluentValidation/6.1.0) on nuget, but `MicroElements.Swashbuckle.FluentValidation` has dependency on it.

**Comment by avgalex** [comment]
try to solve the problem with publishing the other packages

**Comment by avgalex** [comment]
Thank you @petriashev
