### ISSUE TITLE
IComparisonValidator (GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual) for DateTime?

### ISSUE THREAD

**Issue by iMetro** [micro-elements/MicroElements.Swashbuckle.FluentValidation#18]
Hi,
Just checking for the possibility of getting info in the swagger model for DateTime? With a fluent validation rule:
`RuleFor(x => x.StartDateTime).LessThanOrEqualTo(x => x.EndDateTime);`

It would be great to have this represented in the swagger model.
```
searchModel
    startDateTime dateTime
    lessThanOrEqual: endDateTime

    endDateTime dateTime
```
I realize there is no properties in the Schema that would represent MinDateTime or MaxDateTime, but maybe that could be solved in another way...

**Comment by petriashev** [comment]
Schema.Maximum and Schema.Minimum is integer number. But now it can be double (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/7493a079ba25ce6ad9eb6bee83b9483bf8a46a96#diff-1efb7e7b6bf4af623bd684bd379f61b9)
FluentValidation can compare any IComparable value but SwaggerSchema treats minimum and maximum as numbers: https://swagger.io/docs/specification/data-models/data-types/
