### ISSUE TITLE
Swashbuckle v4 and Scoped Dependency Injection.

### ISSUE THREAD

**Issue by VictorioBerra** [micro-elements/MicroElements.Swashbuckle.FluentValidation#23]
https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/pull/22#discussion_r232811495

`ScopedSwaggerMiddleware` is broken.

We need this library to work when scoped dependencies (ie `DbContext`) are injected into `AbstractValidators` (and other validator types). Preferably without using any workarounds.

**Comment by VictorioBerra** [comment]
Can you update the README and remove the workarounds that no longer work or exist? Like `ServiceProviderScopedValidatorFactory`.

**Comment by petriashev** [comment]
I want to remove beta label when this issue will be fixed. Right now I have no time to investigate problem because working on https://github.com/micro-elements/MicroElements.Functional.

**Comment by VictorioBerra** [comment]
Why not just pick up F#? lol

**Comment by WarpSpideR** [comment]
I've been looking at this today and although I can't seem to get the middleware to work with scoped services as per the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-2.2#per-request-middleware-dependencies), I was able to create a validator factory class that would create validators correctly when there are scoped dependencies. 

I'm guessing this is a similar solution to the `ServiceProviderScopedValidatorFactory` that is now missing. I don't know the reasons for the file going awry, or if it would be useful but I can always post a pull request if it will help others.

**Comment by petriashev** [comment]
@WarpSpideR It will help. Post PR or sample please.

**Comment by petriashev** [comment]
Closed with #34
