### ISSUE TITLE
Does not expose minimum or maximum values for GreaterThan,GreaterThanOrEqualTo,LessThan,LessThanOrEqualTo etc.

### ISSUE THREAD

**Issue by barissonmez** [micro-elements/MicroElements.Swashbuckle.FluentValidation#3]
Hi,
Does not expose minimum or maximum values for GreaterThan,GreaterThanOrEqualTo,LessThan,LessThanOrEqualTo etc.

**Comment by petriashev** [comment]
Hi, started work on it.

**Comment by petriashev** [comment]
fixed in https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/commit/2692e8318c6cd3b05b9fb0ac94aea90e21c10b5c
