### ISSUE TITLE
Show rules inside when conditions

### ISSUE THREAD

**Issue by vojtechrojicek** [micro-elements/MicroElements.Swashbuckle.FluentValidation#33]
Hi,
I have `Person` validator like this:
```
RuleFor(x => x.Name).NameValidation();

When(x => x.Address != null, () =>
{
       RuleFor(x => x.Address.Street).MaximumLength(255);
       RuleFor(x => x.Address.PostCode).MaximumLength(20);
       RuleFor(x => x..Address.City).MaximumLength(255);
       RuleFor(x => x.Address.Country).MaximumLength(255);
});
```
Swagger show only rule for `Name` property but ignore rules for `Address` property (`Street`, `PostCode`, etc.).

Am I doing something wrong? Can you please help me how to solve this?

Thanks.

**Comment by petriashev** [comment]
Did you try create validator for Address type?

**Comment by vojtechrojicek** [comment]
Yes I tried that.
Problem is that `Person` can has 2 Addresses. Both are same class `Address` but each has different validation rules. (In my business domain its little more complicated, I am just simplyfiyng that to `Person` with 2 Addresses. I know it is maybe not the best case for two same classes with different validation rules.)
```
RuleFor(x => x.Name).NameValidation();
When(x => x.Address != null, () =>
{
       RuleFor(x => x.Address.Street).MaximumLength(255);
       RuleFor(x => x.Address.PostCode).MaximumLength(20);
       RuleFor(x => x..Address.City).MaximumLength(255);
       RuleFor(x => x.Address.Country).MaximumLength(255);
});
When(x => x.PostAddress != null, () =>
{
       RuleFor(x => x.PostAddress .Street).NotNull().MaximumLength(200);
       RuleFor(x => x.PostAddress .PostCode).NotNull().MaximumLength(20);
       RuleFor(x => x..PostAddress .City).NotNull().MaximumLength(200);
       RuleFor(x => x.PostAddress .Country).NotNull().MaximumLength(200);
});
```

**Comment by petriashev** [comment]
see Swagger (OpenApi) https://swagger.io/specification/#schemaObject
you can attach validation only to type properties

**Comment by vojtechrojicek** [comment]
Ok. 
So, I am not able to do that.

Thanks a lot for quick response.
