### ISSUE TITLE
Update package in NuGet

### ISSUE THREAD

**Issue by vova-lantsov-dev** [micro-elements/MicroElements.Swashbuckle.FluentValidation#36]
Please, upload the last changes to NuGet as 3.0.0-beta2 to be able to work with Swashbuckle 5.0.0-rc3

**Comment by petriashev** [comment]
There were some devops problems. I will release it soon with other changes from main branch

**Comment by vova-lantsov-dev** [comment]
@petriashev really waiting for it :)

**Comment by petriashev** [comment]
see 3.0.0-rc.1
