### ISSUE TITLE
IComparisonValidator (GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual) works only for <int> type

### ISSUE THREAD

**Issue by barissonmez** [micro-elements/MicroElements.Swashbuckle.FluentValidation#4]
Hi,
IComparisonValidator (GreaterThan, GreaterThanOrEqual, LessThan, LessThanOrEqual) works correctly for only int type.
Here is my validator class:
![validatorclass](https://user-images.githubusercontent.com/860041/38126192-a1ee9f60-33f7-11e8-8d86-27744cf663b0.PNG)

Here is the output with MicroElements:
![microelementsoutput](https://user-images.githubusercontent.com/860041/38126201-b5b3a75c-33f7-11e8-8e3c-308f0c2c843a.PNG)

And here is the output of ComponentModel.DataAnnotations:
![componentmodeloutput](https://user-images.githubusercontent.com/860041/38126215-cf40c678-33f7-11e8-9d1b-e360a5998a21.PNG)

"Quantity(int)" field is being exposed correctly but "Deci(float)" and "Price(decimal)" fields are not.

Thanks for your support.

**Comment by petriashev** [comment]
Accepted for next version.
I think to support types: int, float, double.

And I see that NotEmpty for numerics generates minLength: 1.
I am not sure this is right... Should I restrics it to only string?

**Comment by petriashev** [comment]
fixed in https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/commit/e3d9b8436da13cd2ec57f415d3fa87bea26c1734

version 0.5.0

// WARNING: Swashbuckle implements minimum and maximim as int so you will loss fraction part of float and double numbers
