### ISSUE TITLE
ApplyRulesToSchema doesn't work when a property is serialized with a different name.

### ISSUE THREAD

**Issue by KevinSchumm-Limeade** [micro-elements/MicroElements.Swashbuckle.FluentValidation#42]
In the case where you apply a DataMember attribute to a model property and supply a different name, the validation rule won't get applied to the schema.

In Extensions.GetValidatorsForMemberIgnoreCase, the property name won't match the name on the schema and it fails to retrieve the validation rules for the property.

https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/blob/master/src/MicroElements.Swashbuckle.FluentValidation/Extensions.cs#L86

But also, love the library. Thanks for your work :)

**Comment by petriashev** [comment]
look new https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/3.0.0-rc.4
