### ISSUE TITLE
Error ApiModelResolver

### ISSUE THREAD

**Issue by andreslozada** [micro-elements/MicroElements.Swashbuckle.FluentValidation#45]
I'm getting this error:

```
TypeLoadException: Could not load type 'Swashbuckle.AspNetCore.SwaggerGen.IApiModelResolver' from assembly 'Swashbuckle.AspNetCore.SwaggerGen, Version=5.0.0.0, Culture=neutral, PublicKeyToken=d84d99fb0135530a'.
System.Signature.GetSignature(Void* pCorSig, int cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
```

**Environment**
- SO: Windows
- Net Core: 3.0.1
- Swashbuckle.AspNetCore 5.0.0-rc-5
- MicroElements.Swashbuckle.FluentValidation 3.0.0-rc-3

**Comment by davidhenley** [comment]
Confirmed

**Comment by saharati** [comment]
Same...
Is it because .net core 3 is not supported yet?

**Comment by petriashev** [comment]
Net core 3 is supported but new betas was released. I should support it...

**Comment by micahosborne** [comment]
I'm having the same issue

**Comment by petriashev** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/65d2afc70ee6a78bede6993e10fe3d42acebaf45

**Comment by petriashev** [comment]
https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/3.0.0-rc.4

**Comment by andreslozada** [comment]
Great @petriashev I'll update my project tomorrow :) Thanks!
