### ISSUE TITLE
Fluentvalidation MaxLength overrides NotEmpty

### ISSUE THREAD

**Issue by Benjaminmnoer** [micro-elements/MicroElements.Swashbuckle.FluentValidation#50]
Hello!

I have a project where I have the following class I am trying to validate:

```csharp
/// <summary>
/// Interface for person data.
/// </summary>
public interface IPersonData
{
    /// <summary>
    /// Must be nonempty.
    /// </summary>
    string FirstName { get; set; }

    /// <summary>
    /// Must be nonempty.
    /// </summary>
    string Surname { get; set; }
}
```

On the string properties I am trying to add a maximum length validation, with this validator:

```csharp
public class PersonDataValidator : AbstractValidator<IPersonData>
{
    public PersonDataValidator()
    {
        RuleFor(p => p.FirstName).NotEmpty().SetValidator(new MaximumLengthValidator(64));
        RuleFor(p => p.Surname).NotEmpty();
    }
} 
```

However, adding the MaximumLengthValidator overrides the NotEmpty() rule and generates the following OpenAPI documentation:

    "firstName": {
          "description": "Must be nonempty.",
          "maxLength": 64,
          "minLength": 0,
          "type": "string"
    }

minLength here should be 1, and if the order of the validation rules are switched like this:

```csharp
RuleFor(p => p.FirstName).SetValidator(new MaximumLengthValidator(64)).NotEmpty();
```

It generates the following documentation:

    "firstName": {
      "description": "Must be nonempty.",
      "maxLength": 64,
      "minLength": 1,
      "type": "string"
    }

So it would seem like there is an error in the way the rules are read. FluentValidation handles both cases correctly and empty strings are disallowed no matter the order of the rules.

**Comment by petriashev** [comment]
It was fixed in #35
