### ISSUE TITLE
NotNull not working

### ISSUE THREAD

**Issue by bretbas** [micro-elements/MicroElements.Swashbuckle.FluentValidation#55]
Hello, I have a simple rule:
```
RuleFor(x => x.Name).NotNull();
```
but this not working:
```
name*  |  string  nullable: true
```
when I set the attribute `[Required]` --> its works file --> nullable: false

I use:
`Swashbuckle.AspNetCore` --> `5.3.3`
`FluentValidation.AspNetCore` --> `8.6.1`
`MicroElements.Swashbuckle.FluentValidation` --> `3.1.0`

**Comment by bretbas** [comment]
Is anyone here?

**Comment by petriashev** [comment]
Here) busy work.
