### ISSUE TITLE
Ruleset support

### ISSUE THREAD

**Issue by martinobordin** [micro-elements/MicroElements.Swashbuckle.FluentValidation#56]
Are FluentValidation RuleSet supported for the generation of the swagger documentation?

**Comment by petriashev** [comment]
RuleSets are conditional on code level and not supported.
How can it be supported in OpenApi?

**Comment by tomek-anuszkiewicz** [comment]
I have similar issue. You may use them on controller level like this:

```csharp
  public IActionResult Update(
            [CustomizeValidator(RuleSet = RestControllerRuleSets.UpdateRuleSet)]
            Project project)
```
