### ISSUE TITLE
RuleForEach 

### ISSUE THREAD

**Issue by RoyChase** [micro-elements/MicroElements.Swashbuckle.FluentValidation#66]
pr #51 removed processing CollectionPropertyRules.  This means that the rules for collection properties are not output.

If I have ```RuleForEach(sample => sample.Email).EmailAddress();```

How do I get the email validation output in schema?

**Comment by petriashev** [comment]
At the current moment RuleForEach is not supported.
Workaround is to create class Email with own validator. 

I think I can support RuleForEach
