### ISSUE TITLE
Swagger UI does not show information from rules on base classes

### ISSUE THREAD

**Issue by fp-jcorriveau** [micro-elements/MicroElements.Swashbuckle.FluentValidation#77]
See this exemple

```c#
// abstract
public abstract class  AbstractInstitutionModel
{
    public string Name { get; set; }
}

// class
public class InstitutionModel : AbstractInstitutionModel
{
}

// fluent validator
public class AbstractInstitutionModelValidator : AbstractValidator<AbstractInstitutionModel>
{
    public InstitutionModelValidator()
    {
        RuleFor(p => p.Name)
            .NotEmpty()
            .MaximumLength(100);
    }
}
```

The schemas information in SwaggerUI does not mark the Name as required with a maximum length of 100.
As I don't want to put data annotations AND create rules with FluentValidation, I find it is a bit sad.

As a workaround, I have to specify the rules in the inheriting class, but that not what I expected because if I use data annotations instead, the information is there.

**Comment by bcronje** [comment]
I think this is a FluentValidation issue and not this library issue. The following works for me, not sure if that is the right way to do it or not:

```
// abstract
public abstract class  AbstractInstitutionModel
{
    public string Name { get; set; }
}

// fluent validator
public class AbstractInstitutionModelValidator : AbstractValidator<AbstractInstitutionModel>
{
    public AbstractInstitutionModelValidator()
    {
        RuleFor(p => p.Name)
            .NotEmpty()
            .MaximumLength(100);
    }
}

// class
public class InstitutionModel : AbstractInstitutionModel
{
}



// fluent validator
public class InstitutionModelValidator : AbstractValidator<InstitutionModel>
{
    public InstitutionModelValidator()
    {
        Include(new AbstractInstitutionModelValidator());
    }
}
```

**Comment by fp-jcorriveau** [comment]
It is effectively working when creating the validator on the concrete class, but I wonder...
Let's say you have 
```c#
public abstract class  AbstractInstitutionModel
{
    [Required]
    public string Name { get; set; }
}

public class  InstitutionForCreationModel : AbstractInstitutionModel {}
public class  InstitutionForUpdateModel : AbstractInstitutionModel {}
```

Swashbuckle will generate the documentation accordingly.

And since the name is always required, I don't really want to duplicate the validator...
I will ask the FluentValidator team

**Comment by bcronje** [comment]
Please report back if you can, because I had the same scenario and my conclusion at the time was the code I posted above. Maybe I missed something.

**Comment by fp-jcorriveau** [comment]
hmm here is their answer
 
https://github.com/FluentValidation/FluentValidation/issues/1660#issuecomment-787987322

**Comment by petriashev** [comment]
@bcronje Thanks for help!

**Comment by petriashev** [comment]
@fp-jcorriveau  Does FV validates your example correct? If FV does work as expected then reopen issue.

**Comment by fp-jcorriveau** [comment]
It actually might not be a real-life situation as I will need to create a validator for the concrete classes or else FV will not validate them.

**Comment by petriashev** [comment]
New version of MicroElements.FluentValidation will support this feature. (6.0.0 - beta.3)
