### ISSUE TITLE
Fails to run with FluentValidation 10 Preview 2

### ISSUE THREAD

**Issue by wonea** [micro-elements/MicroElements.Swashbuckle.FluentValidation#78]
I upgraded my API to FluentValidation 10 Preview 2, and the API fails to start with a Swagger error. I tried the workarounds 1 & 2 but sadly these did not fix the problem.

![image](https://user-images.githubusercontent.com/557192/110496273-39c8d680-80ed-11eb-8f0b-a35d890491e4.png)

**Comment by petriashev** [comment]
FluentValidation 10 is not supported yet.

**Comment by wonea** [comment]
Okay, thanks. I'll update my packages once support is in. Need to use FluentValidation 10 for async support.

**Comment by rcollette** [comment]
I think this can be closed now, but it seems to be pegged at 10.0.0 and will not run with patch releases, which it should.

**Comment by gokhanabatay** [comment]
When dou you plan to support FluentValidation 10

**Comment by petriashev** [comment]
I will try to spend some time in May. This project supported in my spare time and my employer does not sponsor it.

**Comment by petriashev** [comment]
Please check https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/5.0.0-rc.1

**Comment by wonea** [comment]
Sorry, just tried to upgrade but it's doesn't work with FluentValidaton 10.2.3
![image](https://user-images.githubusercontent.com/557192/121217349-a9c83380-c879-11eb-97ad-8ae0236f6aa9.png)

**Comment by rcollette** [comment]
Try RC2.  There may be a new setup configuration that you have not implemented see thread.
https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/issues/88#issuecomment-853403654

**Comment by wonea** [comment]
@rcollette Thanks, that solved the issue for me.
