### ISSUE TITLE
Adding a simple Length validation to a string field should not make the field non-nullable

### ISSUE THREAD

**Issue by immsb1138** [micro-elements/MicroElements.Swashbuckle.FluentValidation#79]
Given this class and validator

```
    public class Foo
    {
        public string Bar { get; set; }
    }

    public class FooValidator : AbstractValidator<Foo>
    {
        public FooValidator()
        {
            RuleFor(f => f.Bar).Length(3, 100);
        }
    }

```

The generated schema definition for Foo is 

```
      "Foo": {
        "type": "object",
        "properties": {
          "bar": {
            "maxLength": 100,
            "minLength": 3,
            "type": "string"
          }
        },
        "additionalProperties": false
      },
```

The bar property is not indicated to be nullable, however the actual FluentValidation behavior treats a null value for Bar as valid. The schema definition for the bar property should include ` "nullable": true `.

The nullable attribute of the bar property in the swagger definition should only be excluded if my FluentValidation rule had been something like

`RuleFor(f => f.Bar).NotNull().Length(3, 100)`

The same invalid result is generated when using the MinimumLength FluentValidation function in place of the Length function.

**Comment by petriashev** [comment]
Interesting... 
Yes FV does not checks string value if it is null:
```
		protected override bool IsValid(PropertyValidatorContext context) {
			if (context.PropertyValue == null) return true;
...
```
I will think about it :) thanks for report!

**Comment by petriashev** [comment]
@immsb1138  Can you check 4.3.0-rc.1?

**Comment by immsb1138** [comment]
Looks great. I tested `.Length(3, 100)`, `.MinimumLength(3).MaximumLength(10)`, `.Length(3, 100).NotEmpty()`, and `.NotEmpty().MinimumLength(3).MaximumLength(10)`. All worked as I would expect. The ones without `NotEmpty()` included `"nullable": true` and the ones with `NotEmpty()` did not. Awesome!
