### ISSUE TITLE
Add support for override of property names

### ISSUE THREAD

**Issue by Sergey-Terekhin** [micro-elements/MicroElements.Swashbuckle.FluentValidation#80]
Hi!
Thank you for the great library!

Could you add support of overrided property names by attributes? For example, we have following model:
```c#
public class BestShot
    {
        [JsonProperty("photo")]
        public string Link { get; set; }

        [JsonProperty("zone")]
        public string Area { get; set; }
    }
```
Json properties are received from external system and can not be changed, but in our code we wish to work with more clear property names, so we use `[JsonProperty]` attribute

In such case validation rules are not applied because they does not know about OpenAPI properties generated by attributes. The only place it could be done is inside `FluentValidationRules`, but where istoo many internal stuff to override it 

May be it could be done introducing some sort of map between .Net Property name and OpenAPI name like
```c#
new Dictionary<string, string>{{nameof(BestShot.Link), "photo"}}
```

attached to the type somewhere in `AddFluentValidationRules` options

**Comment by petriashev** [comment]
Hi Sergey!
1. Do you use Newtonsoft?
2. What property do you see in swagger? photo or Link?

I think MicroElements.Swashbuckle.FluentValidation should provide something like INamingConvention or try to support existent naming support fro OpenAPI

**Comment by Sergey-Terekhin** [comment]
1. We use Newtonsoft
2. In Swagger I see photo as `expected`, but validator works for the `Link` property (as expected too) and does not know anything about property names in OpenAPI

The only place where mapping is possible is documentation filter - it knows about type and about open api schema. But we need to define mapping somehow - in dictionary or in other way (read from attribute for example). 

Some interface which I could implement would be great

**Comment by petriashev** [comment]
Sorry I am very busy at work and other projects. I remember your ussue

**Comment by petriashev** [comment]
Please check https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/5.0.0-rc.1

**Comment by petriashev** [comment]
Is your issue resolved?

**Comment by Sergey-Terekhin** [comment]
I'll try a bit later. Next week possible
