### ISSUE TITLE
SchemaFilterContext is Obsolete

### ISSUE THREAD

**Issue by david-driscoll** [micro-elements/MicroElements.Swashbuckle.FluentValidation#81]
I've noted that the SchemaFilterContext property is now obsolete on the `RuleContext`.

Would it be possible to have the schema type (and perhaps propertyinfo / fieldinfo?) added to the `RuleContext`?  I've found it useful to be able to reflect over the type or the property of the type to make some schema changes.

Thanks!

**Comment by petriashev** [comment]
Thanks for issue.
SchemaFilterContext is marked as obsolete because I have plans to support other schema generators (NSwag for example).
I will have in mind that type information is needed for some cases.

Can I know know do you use SchemaFilterContext?

**Comment by petriashev** [comment]
Please check https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/5.0.0-rc.1
