### ISSUE TITLE
Support FV 10 - Create new nuget version

### ISSUE THREAD

**Issue by DennisKae** [micro-elements/MicroElements.Swashbuckle.FluentValidation#84]
Hi @petriashev,
your commit [dbd23773308723394cef0c4da965d2b91fc0a616](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/commit/dbd23773308723394cef0c4da965d2b91fc0a616) added support for FluentValidation > Version 10. 
Can you please create a new version and push it to nuget?

**Comment by petriashev** [comment]
check 5.0.0-rc.1 on nuget (https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/5.0.0-rc.1)

**Comment by DennisKae** [comment]
Oh, I missed that. Thanks a lot for your hint!
