### ISSUE TITLE
InvalidOperationException: Cannot resolve scoped service 'FluentValidation.IValidatorFactory' from root provider.

### ISSUE THREAD

**Issue by andrewwilkin** [micro-elements/MicroElements.Swashbuckle.FluentValidation#90]
I've added Swashbuckle to a project based upon Jason Taylor's clean architecture. This makes use of Fluent Validation.

When I add "AddFluentValidationRules()" in the Swagger Config it falls over with the following error:
InvalidOperationException: Cannot resolve scoped service 'FluentValidation.IValidatorFactory' from root provider.

Yet I can see it in the services as a scoped service, and I've added it to a controller to check that it resolves and it does. It's also working for the validation.

Any pointers?

**Comment by andrewwilkin** [comment]
FYI:
Also tried services.AddFluentValidationRulesToSwagger();

**Comment by VILLAN3LL3** [comment]
Same problem here. I additionally added `config.ValidatorFactoryType = typeof(HttpContextServiceProviderValidatorFactory);` but without success.

**Comment by Prologh** [comment]
Try version `5.1.0-rc.2`

#89

**Comment by petriashev** [comment]
I will release it today (5.1.0)

**Comment by petriashev** [comment]
done

**Comment by lsiepel** [comment]
Maybe I'm missing something, but 5.1.0 is causing the same problem for me.
`InvalidOperationException: Cannot resolve scoped service 'FluentValidation.IValidatorFactory' from root provider.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ActivatorUtilities+ConstructorMatcher.CreateInstance(IServiceProvider provider)
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, object[] parameters)`

```
            services
               .AddProblemDetails(ConfigureProblemDetails)
               .AddMvc()
               .AddProblemDetailsConventions()
               .AddFluentValidation(o =>
               {
                   o.RegisterValidatorsFromAssemblyContaining<Startup>();
                   o.ValidatorFactoryType = typeof(HttpContextServiceProviderValidatorFactory);
               });
```

Is there any addiotional configuration needed for the fix in 5.1.0 to work?

**Comment by Prologh** [comment]
Did you add this line your Startup? It's brand new.

```C#
services.AddFluentValidationRulesToSwagger();
```

See more in updated [README](https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation#2-change-startupcs).

**Comment by lsiepel** [comment]
Yep sorry, i had to replace `.AddFluentValidationRules(); `  with  `services.AddFluentValidationRulesToSwagger();`
I didn't notice this obsolete warning. Thanks

**Comment by VILLAN3LL3** [comment]
I updated to 5.1.0 today and could remove all workaround code for this issue. It's working now - thank you!
