### ISSUE TITLE
Rule with overridden property name unexpectedly applied to property

### ISSUE THREAD

**Issue by icnocop** [micro-elements/MicroElements.Swashbuckle.FluentValidation#94]
Hi.

Thank you for MicroElements.Swashbuckle.FluentValidation.

When I create a rule with an overridden property name the validation rule is applied to the property that was set to override.

For example, update the Person and PersonValidator classes in ".\samples\SampleWebApi\Controllers\PersonController.cs" as follows:
```
    public class Person
    {
        public string Name { get; set; }

        public List<string> Emails { get; set; } = new List<string>();

        private string FirstName
        {
            get
            {
                return this.Name == null ? null :
                        !this.Name.Contains(" ") ? this.Name :
                        this.Name.Split(new char[] { ' ' }).FirstOrDefault();
            }
        }

        private string LastName
        {
            get
            {
                return this.Name == null ? null :
                        !this.Name.Contains(" ") ? null :
                        this.Name.Split(new char[] { ' ' }).Skip(1).FirstOrDefault();
            }
        }

        [UsedImplicitly]
        public class PersonValidator : AbstractValidator<Person>
        {
            public PersonValidator()
            {
                this.RuleFor(x => x.FirstName)
                    .MaximumLength(50)
                    .OverridePropertyName(x => x.Name);

                this.RuleFor(x => x.LastName)
                    .MaximumLength(50)
                    .OverridePropertyName(x => x.Name);

                RuleForEach(x => x.Emails).EmailAddress();
            }
        }
    }
```

The rules are applied on the FirstName and LastName private properties.
There isn't a rule directly applied to the Name property.
However, the swagger.json is generated and indicates the maximum length of the Name property is 50 characters, which is unexpected.

Actually the maximum length of the Name property is 101 characters, but I don't expect that to be applied to swagger.json in this case.

Any ideas on what can be done in this case to either set the maximum length of the Name property to 101 or to not even apply the rule to the generated swagger.json?

Trying to set a rule explicitly on the Name property to work-around this issue doesn't get applied to swagger.json (swagger.json is still generated indicating the Name property has a maximum length of 50 characters):
```
this.RuleFor(x => x.Name)
    .MaximumLength(101);
```

I'm currently using 
```
<TargetFramework>netcoreapp3.1</TargetFramework>
<PackageReference Include="FluentValidation.AspNetCore" Version="9.2.0" />
<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
<PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="4.3.0" />
```

Thank you.

**Comment by petriashev** [comment]
Why do you use OverridePropertyName? 

Remove OverridePropertyName and add code:
```
this.RuleFor(x => x.Name)
    .MaximumLength(101);
```

**Comment by icnocop** [comment]
I use OverridePropertyName so the validation error key indicates the issue is with the Name field and not FirstName.
The FirstName field is private and doesn't actually exist on the API.

For example, with the following rules:
```
this.RuleFor(x => x.FirstName)
    .MaximumLength(50)
    .OverridePropertyName(x => x.Name)
    .WithName("First Name");

this.RuleFor(x => x.LastName)
    .MaximumLength(50)
    .OverridePropertyName(x => x.Name)
    .WithName("Last Name");
```
Trying to pass first name with 51 characters like `"Name": "123456789012345678901234567890123456789012345678901 last"` will produce the expected error message:
```
"errors": {
    "Name": [
      "The length of 'First Name' must be 50 characters or fewer. You entered 51 characters.",
    ]
  }
```

Notice the error key is `"Name"` and the error message indicates `'First Name'`.

Thank you.

**Comment by petriashev** [comment]
MicroElements.Swashbuckle.FluentValidation matches rules with OpenApi properties by name so tries to merge several maxLength to one (most strict).
I can opt in behaviour that matches rule by member name (can impact present behaviour, should be tested).

If I match by member name then OpenApi becomes:

```
"properties": {
      "name": {
        "maxLength": 101,
        "type": "string",
        "nullable": true
      },
      "emails": {
        "type": "array",
        "items": {
          "type": "string",
          "format": "email"
        },
        "nullable": true
      }
    },
```

**Comment by petriashev** [comment]
Found a bug. Present NameResolver works as expected. Wait for bugfix.

**Comment by petriashev** [comment]
Please check 5.3.0

**Comment by icnocop** [comment]
Thank you very much for the quick fix!

It now works as expected!

👍
